apiVersion: v2
name: product-api
description: A Helm chart for the Product API
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "13.2.24"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
